import { Question, Category, Difficulty } from "@/types";

// 182 questions — 6 months of daily content starting 2026-03-01
// Categories: TIME(26) HUMAN_BODY(26) SCALE(32) SPACE(22) NATURE(26) HISTORY(22) WILD_CARD(28)
const QUESTIONS: Omit<Question, "_id">[] = [
  // ============================================================
  // TIME (26)
  // ============================================================
  {
    date: "2026-03-01",
    questionNumber: 1,
    question: "How long is 1 billion seconds?",
    answer: 31.7,
    unit: "years",
    explanation:
      "There are about 31.5 million seconds in a year, making 1 billion seconds roughly 31.7 years. For comparison, 1 million seconds is only about 11.5 days.",
    source: "https://en.wikipedia.org/wiki/1,000,000,000",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-02",
    questionNumber: 2,
    question: "How many years would it take to walk to the Moon — non-stop, 24/7?",
    answer: 9,
    unit: "years",
    explanation:
      "Walking at 3 mph without stopping, the 238,900-mile trip to the Moon would take about 9 years. Better pack a very long playlist.",
    source: "https://www.spaceanswers.com/space-exploration/how-long-would-it-take-to-walk-to-the-moon/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-03",
    questionNumber: 3,
    question: "How many days old is someone who just turned 30?",
    answer: 10950,
    unit: "days",
    explanation:
      "A 30-year-old has lived about 10,950 days. That feels shockingly small — the average human lifespan is only around 28,000–30,000 days total.",
    source: "https://www.cdc.gov/nchs/fastats/life-expectancy.htm",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-04",
    questionNumber: 4,
    question: "How many minutes per day does the average person spend on their phone?",
    answer: 240,
    unit: "minutes",
    explanation:
      "The average person spends roughly 4 hours (240 minutes) on their phone every day — that adds up to about 60 full days per year staring at a screen.",
    source: "https://www.statista.com/statistics/1045353/mobile-device-daily-usage-time-in-the-us/",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-05",
    questionNumber: 5,
    question: "How many hours does the average person spend eating over their entire lifetime?",
    answer: 32000,
    unit: "hours",
    explanation:
      "At roughly 67 minutes of eating per day, the average person spends about 32,000 hours — or roughly 3.6 years — eating over a 79-year life.",
    source: "https://www.usda.gov/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-06",
    questionNumber: 6,
    question: "How many days would it take to count to 1 million, at one number per second?",
    answer: 11.6,
    unit: "days",
    explanation:
      "Counting non-stop at one number per second, you'd hit 1 million in just 11.6 days. But counting to 1 billion the same way would take over 31 years.",
    source: "https://en.wikipedia.org/wiki/Names_of_large_numbers",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-07",
    questionNumber: 7,
    question: "How many seconds are in one year?",
    answer: 31536000,
    unit: "seconds",
    explanation:
      "There are 31,536,000 seconds in a year (60 × 60 × 24 × 365). Scientists and engineers use this number constantly — and most people have no idea it's that large.",
    source: "https://www.nist.gov/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-08",
    questionNumber: 8,
    question: "How many years of their life does the average person spend asleep?",
    answer: 26,
    unit: "years",
    explanation:
      "Sleeping 8 hours a night over a 79-year life adds up to about 26 years — roughly one third of your entire existence spent unconscious.",
    source: "https://www.sleepfoundation.org/how-sleep-works/how-much-sleep-do-we-really-need",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-09",
    questionNumber: 9,
    question: "How many years ago did the dinosaurs go extinct?",
    answer: 66000000,
    unit: "years ago",
    explanation:
      "The non-avian dinosaurs went extinct about 66 million years ago, after an asteroid impact. Modern humans have only existed for about 300,000 years — we're a very new arrival.",
    source: "https://www.britannica.com/animal/dinosaur/The-Cretaceous-extinction",
    category: "TIME" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-10",
    questionNumber: 10,
    question: "How old is the universe, in years?",
    answer: 13800000000,
    unit: "years",
    explanation:
      "The universe is approximately 13.8 billion years old, determined by measuring the cosmic microwave background radiation. Earth didn't form until about 9 billion years after the Big Bang.",
    source: "https://science.nasa.gov/universe/overview/",
    category: "TIME" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-11",
    questionNumber: 11,
    question: "How many years ago did modern humans first appear on Earth?",
    answer: 300000,
    unit: "years ago",
    explanation:
      "Homo sapiens emerged roughly 300,000 years ago in Africa. To put it in perspective, if Earth's entire history were one year, humans showed up at 11:37 PM on December 31st.",
    source: "https://www.smithsonianmag.com/science-nature/when-where-did-modern-humans-first-appear-180969854/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-12",
    questionNumber: 12,
    question: "How many days is the average human lifespan?",
    answer: 28835,
    unit: "days",
    explanation:
      "The average global lifespan of about 79 years equals roughly 28,835 days. That's only around 28,000 mornings to wake up — which is why every single one counts.",
    source: "https://www.who.int/data/gho/indicator-metadata-registry/imr-details/65",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-13",
    questionNumber: 13,
    question: "How many years ago was the earliest known writing system invented?",
    answer: 5200,
    unit: "years ago",
    explanation:
      "Cuneiform, the world's oldest writing system, was developed in Mesopotamia around 3200 BC — about 5,200 years ago. It started as accounting tablets tracking grain and livestock.",
    source: "https://www.britishmuseum.org/blog/cuneiform",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-14",
    questionNumber: 14,
    question: "How many years did construction of the Great Wall of China span across history?",
    answer: 2000,
    unit: "years",
    explanation:
      "The Great Wall was built, expanded, and rebuilt across multiple dynasties spanning roughly 2,000 years — from the 7th century BC through the Ming Dynasty in the 1600s.",
    source: "https://www.britannica.com/topic/Great-Wall-of-China",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-15",
    questionNumber: 15,
    question: "How many minutes does it take the International Space Station to orbit Earth once?",
    answer: 92,
    unit: "minutes",
    explanation:
      "The ISS orbits Earth at 17,500 mph and completes a full lap in about 92 minutes — meaning astronauts on board witness 16 sunrises and sunsets every single day.",
    source: "https://www.nasa.gov/international-space-station/facts-and-figures/",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-16",
    questionNumber: 16,
    question: "How many inches does human hair grow in one year?",
    answer: 6,
    unit: "inches",
    explanation:
      "Human hair grows about 6 inches per year, or half an inch per month. Hair grows fastest between the ages of 15–30, and growth slows significantly as we age.",
    source: "https://www.aad.org/public/everyday-care/hair-scalp-care/hair/hair-loss-vs-hair-shedding",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-17",
    questionNumber: 17,
    question: "How many days is 1 million minutes?",
    answer: 694,
    unit: "days",
    explanation:
      "One million minutes is 694 days — just under two years. It sounds like an eternity until you realize 1 billion minutes is closer to 1,902 years.",
    source: "https://www.wolframalpha.com/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-18",
    questionNumber: 18,
    question: "How many years did it take to build the Eiffel Tower?",
    answer: 2.2,
    unit: "years",
    explanation:
      "The Eiffel Tower was built in just 2 years and 2 months (1887–1889), using 300 workers and 2.5 million rivets. Critics called it an eyesore — Parisians now call it home.",
    source: "https://www.toureiffel.paris/en/the-monument/history",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-19",
    questionNumber: 19,
    question: "How many years did the Byzantine Empire last?",
    answer: 1123,
    unit: "years",
    explanation:
      "The Byzantine Empire lasted from 330 AD (founding of Constantinople) until 1453 AD — a remarkable 1,123 years. Most people don't even know it existed that long.",
    source: "https://www.britannica.com/place/Byzantine-Empire",
    category: "TIME" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-20",
    questionNumber: 20,
    question: "How old was the oldest person who ever lived, in years?",
    answer: 122,
    unit: "years",
    explanation:
      "Jeanne Calment of France lived to 122 years and 164 days — the oldest verified human lifespan. She was born in 1875 and met Vincent van Gogh as a teenager.",
    source: "https://www.guinnessworldrecords.com/world-records/oldest-person",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-21",
    questionNumber: 21,
    question: "How many minutes does it take sunlight to travel from the Sun to Pluto?",
    answer: 330,
    unit: "minutes",
    explanation:
      "At the speed of light, it takes about 330 minutes (5.5 hours) for sunlight to reach Pluto. By that point, Pluto receives about 1,600 times less light than Earth does.",
    source: "https://solarsystem.nasa.gov/planets/dwarf-planets/pluto/in-depth/",
    category: "TIME" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-22",
    questionNumber: 22,
    question: "How many years does it take light to travel from the nearest star to Earth?",
    answer: 4.24,
    unit: "years",
    explanation:
      "Proxima Centauri, our nearest stellar neighbor, is 4.24 light-years away. Even traveling at Voyager 1's speed, it would take over 73,000 years to reach it.",
    source: "https://www.esa.int/Science_Exploration/Space_Science/Proxima_Centauri",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-23",
    questionNumber: 23,
    question: "How long did it take to build the Great Pyramid of Giza, in years?",
    answer: 20,
    unit: "years",
    explanation:
      "Most Egyptologists estimate the Great Pyramid took about 20 years to complete, requiring roughly 100,000 workers. That's about 800 tons of stone placed every single day.",
    source: "https://www.nationalgeographic.com/history/article/how-was-the-great-pyramid-built",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-24",
    questionNumber: 24,
    question: "How many years ago did our ancestors first control fire?",
    answer: 1000000,
    unit: "years ago",
    explanation:
      "Evidence suggests early humans controlled fire at least 1 million years ago in South Africa. Cooking with fire is believed to have dramatically changed our brain development.",
    source: "https://www.smithsonianmag.com/science-nature/archaeology-fire-use-humans-180950210/",
    category: "TIME" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-25",
    questionNumber: 25,
    question: "What is the average one-way commute time in the United States, in minutes?",
    answer: 27,
    unit: "minutes",
    explanation:
      "The average American commutes 27 minutes each way — 54 minutes per day, or roughly 200 hours per year spent commuting. That's over 8 full days sitting in traffic or transit annually.",
    source: "https://www.census.gov/library/stories/2021/03/average-time-americans-spend-commuting.html",
    category: "TIME" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-03-26",
    questionNumber: 26,
    question: "How many Earth days does it take Mars to complete one orbit around the Sun?",
    answer: 687,
    unit: "Earth days",
    explanation:
      "A Martian year lasts 687 Earth days — nearly two of our years. If you were born on Mars, you'd be about half your Earth age.",
    source: "https://solarsystem.nasa.gov/planets/mars/in-depth/",
    category: "TIME" as Category,
    difficulty: "medium" as Difficulty,
  },

  // ============================================================
  // HUMAN BODY (26)
  // ============================================================
  {
    date: "2026-03-27",
    questionNumber: 27,
    question: "How many times does your heart beat in one day?",
    answer: 100000,
    unit: "beats",
    explanation:
      "At roughly 70 beats per minute, your heart beats about 100,000 times every day — over 2.5 billion beats in an average lifetime, without ever taking a break.",
    source: "https://www.heart.org/en/health-topics/heart-failure/what-is-heart-failure",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-28",
    questionNumber: 28,
    question: "How many cells are in the human body?",
    answer: 37200000000000,
    unit: "cells",
    explanation:
      "Your body contains roughly 37.2 trillion cells. Even more mind-blowing: bacterial cells in and on your body number roughly the same. You are almost as much bacteria as you are human.",
    source: "https://pubmed.ncbi.nlm.nih.gov/23829164/",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-03-29",
    questionNumber: 29,
    question: "How many miles of blood vessels are in the human body?",
    answer: 60000,
    unit: "miles",
    explanation:
      "Your body has about 60,000 miles of blood vessels — enough to circle the Earth more than twice. Most are capillaries so tiny that red blood cells must pass through single-file.",
    source: "https://www.fi.edu/heart/blood-vessels",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-30",
    questionNumber: 30,
    question: "How many taste buds does the average adult have?",
    answer: 10000,
    unit: "taste buds",
    explanation:
      "Adults have about 10,000 taste buds, each containing 50–100 receptor cells. They completely regenerate every 1–2 weeks. By age 60, you may have half as many — which is why food tastes blander as you age.",
    source: "https://www.ncbi.nlm.nih.gov/books/NBK279408/",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-03-31",
    questionNumber: 31,
    question: "How many breaths does the average person take in one day?",
    answer: 22000,
    unit: "breaths",
    explanation:
      "You take about 22,000 breaths every day — roughly 15–20 per minute. Over a lifetime, that's around 600 million breaths, almost all of them completely unconscious.",
    source: "https://www.lung.org/lung-health-diseases/how-lungs-work",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-01",
    questionNumber: 32,
    question: "How many neurons are in the human brain?",
    answer: 86000000000,
    unit: "neurons",
    explanation:
      "The human brain contains about 86 billion neurons. Each neuron can connect to up to 10,000 others, creating roughly 100 trillion connections — more than all the stars in the Milky Way.",
    source: "https://pubmed.ncbi.nlm.nih.gov/19226510/",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-02",
    questionNumber: 33,
    question: "How many bones does an adult human body have?",
    answer: 206,
    unit: "bones",
    explanation:
      "Adults have 206 bones — but babies are born with about 270. Many fuse together during childhood. About half of all your bones are in your hands and feet.",
    source: "https://www.britannica.com/science/human-skeleton",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-03",
    questionNumber: 34,
    question: "How many individual hairs are on a typical human head?",
    answer: 100000,
    unit: "hairs",
    explanation:
      "The average head has about 100,000 hairs. You naturally shed 50–100 hairs per day and regrow them. Blondes tend to have more hairs; redheads typically the fewest.",
    source: "https://www.aad.org/public/everyday-care/hair-scalp-care/hair/hair-growth",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-04",
    questionNumber: 35,
    question: "How many red blood cells are in the human body?",
    answer: 25000000000000,
    unit: "red blood cells",
    explanation:
      "Your body contains roughly 25 trillion red blood cells. Every second, your bone marrow produces about 2 million new ones to replace those that wear out.",
    source: "https://www.ncbi.nlm.nih.gov/books/NBK2263/",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-05",
    questionNumber: 36,
    question: "How many steps does the average person take per day?",
    answer: 7500,
    unit: "steps",
    explanation:
      "The average person takes around 7,500 steps per day. Over a lifetime, that's roughly 100,000 miles — about 4 trips around the circumference of the Earth.",
    source: "https://www.medicinenet.com/how_many_steps_a_day_is_considered_active/article.htm",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-06",
    questionNumber: 37,
    question: "How many words does the average person speak in a day?",
    answer: 16000,
    unit: "words",
    explanation:
      "People average about 16,000 words per day. Contrary to popular belief, studies show men and women speak roughly the same amount — the '20,000 vs. 7,000 words' myth has been debunked.",
    source: "https://www.science.org/doi/10.1126/science.1139940",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-07",
    questionNumber: 38,
    question: "How many dead skin cells does your body shed every hour?",
    answer: 35000,
    unit: "skin cells",
    explanation:
      "You shed about 30,000–40,000 skin cells every hour. In a year, you shed roughly the equivalent of your entire outer skin layer 8–9 times. Much of household dust is actually human skin.",
    source: "https://www.livescience.com/9548-dead-skin-cells-home.html",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-08",
    questionNumber: 39,
    question: "How many feet long is the entire human digestive system?",
    answer: 30,
    unit: "feet",
    explanation:
      "From mouth to exit, the human digestive system is about 30 feet long. The small intestine alone is around 20 feet — tightly coiled to fit inside your abdomen.",
    source: "https://www.hopkinsmedicine.org/health/wellness-and-prevention/the-gut-where-bacteria-and-immune-system-meet",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-09",
    questionNumber: 40,
    question: "How many pints of blood does the average adult human body contain?",
    answer: 10,
    unit: "pints",
    explanation:
      "The average adult body holds about 10 pints (roughly 1.25 gallons) of blood. Your heart pumps this entire blood supply around your body about once every minute.",
    source: "https://www.redcrossblood.org/donate-blood/how-to-donate/how-blood-donations-help/blood-needs-blood-supply.html",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-10",
    questionNumber: 41,
    question: "How many pounds does the human brain weigh?",
    answer: 3,
    unit: "pounds",
    explanation:
      "The average adult brain weighs about 3 pounds (1.4 kg) — roughly the weight of a small cantaloupe. Despite being only 2% of your body weight, it consumes 20% of your energy.",
    source: "https://www.health.harvard.edu/mind-and-mood/protect-your-brain-from-stress",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-11",
    questionNumber: 42,
    question: "How many times does your blood fully circulate through your body each day?",
    answer: 1440,
    unit: "times",
    explanation:
      "Your heart pumps blood through your entire circulatory system roughly once per minute — about 1,440 complete circuits every single day. At rest, it takes about 60 seconds for blood to make the full trip.",
    source: "https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-12",
    questionNumber: 43,
    question: "How many muscles are in the human body?",
    answer: 600,
    unit: "muscles",
    explanation:
      "The human body has approximately 600 muscles, making up about 40% of total body weight. It takes 43 muscles to frown but only 17 to smile — though the exact numbers are debated.",
    source: "https://www.britannica.com/science/human-muscle-system",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-13",
    questionNumber: 44,
    question: "How many gallons of blood does your heart pump in one day?",
    answer: 2000,
    unit: "gallons",
    explanation:
      "Your heart pumps roughly 2,000 gallons of blood every day — enough to fill a small tanker truck. Over a 79-year lifetime, that's about 56 million gallons.",
    source: "https://www.heart.org/en/healthy-living/fitness/fitness-basics/aha-recs-for-physical-activity-in-adults",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-14",
    questionNumber: 45,
    question: "How many times does a person blink their eyes in one day?",
    answer: 15000,
    unit: "blinks",
    explanation:
      "You blink about 15,000 times per day, or 10–15 times per minute. Blinking keeps your eyes lubricated and clears debris. If you read all day, you blink significantly less without realizing it.",
    source: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3577496/",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-15",
    questionNumber: 46,
    question: "How fast do the fastest nerve impulses travel, in miles per hour?",
    answer: 268,
    unit: "mph",
    explanation:
      "The fastest nerve signals travel at up to 120 meters per second — about 268 mph. That's faster than most commercial aircraft on takeoff. Pain signals are much slower, which is why you sometimes see the hurt before you feel it.",
    source: "https://www.scientificamerican.com/article/how-fast-does-the-human-body-conduct-impulses/",
    category: "HUMAN_BODY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-16",
    questionNumber: 47,
    question: "What percentage of the human body is water?",
    answer: 60,
    unit: "percent",
    explanation:
      "About 60% of the adult human body is water. The percentage is higher in infants (75%) and lower in the elderly. The brain is about 73% water, and even bones are roughly 31% water.",
    source: "https://www.usgs.gov/special-topics/water-science-school/science/water-you-water-and-human-body",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-17",
    questionNumber: 48,
    question: "How many dreams does the average person have each night?",
    answer: 5,
    unit: "dreams",
    explanation:
      "People typically have 4–6 dreams per night, mostly during REM sleep cycles. Most are forgotten within minutes of waking. You spend about 2 hours per night actively dreaming.",
    source: "https://www.sleepfoundation.org/dreams",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-18",
    questionNumber: 49,
    question: "How many inches do your fingernails grow in one year?",
    answer: 1.5,
    unit: "inches",
    explanation:
      "Fingernails grow about 1.5 inches per year (3.5 mm/month). Toenails grow about half as fast. Nails grow faster in summer, on your dominant hand, and on your longer fingers.",
    source: "https://www.aad.org/public/everyday-care/nail-care-secrets/basics/nail-growth",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-04-19",
    questionNumber: 50,
    question: "How many pounds of dead skin does the average person shed per year?",
    answer: 8,
    unit: "pounds",
    explanation:
      "The average person sheds about 8 pounds of dead skin cells per year — roughly the weight of a newborn baby. Your entire outer skin layer replaces itself completely every few weeks.",
    source: "https://www.livescience.com/9548-dead-skin-cells-home.html",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-20",
    questionNumber: 51,
    question: "How many feet of DNA are in a single human cell?",
    answer: 6,
    unit: "feet",
    explanation:
      "Each human cell contains about 6 feet of DNA tightly coiled inside a nucleus smaller than a grain of sand. If you unraveled all the DNA in your body, it would stretch roughly 42 billion miles — past Pluto and back.",
    source: "https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet",
    category: "HUMAN_BODY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-21",
    questionNumber: 52,
    question: "How many teeth does an adult human have (including wisdom teeth)?",
    answer: 32,
    unit: "teeth",
    explanation:
      "Adults have 32 permanent teeth in total. However, about 35% of people never develop their wisdom teeth, so many adults have 28. Sharks, by contrast, can grow and lose over 30,000 teeth in a lifetime.",
    source: "https://www.mouthhealthy.org/en/az-topics/t/teeth",
    category: "HUMAN_BODY" as Category,
    difficulty: "easy" as Difficulty,
  },

  // ============================================================
  // SCALE (32)
  // ============================================================
  {
    date: "2026-04-22",
    questionNumber: 53,
    question: "How many photos are taken worldwide every day?",
    answer: 1400000000,
    unit: "photos",
    explanation:
      "About 1.4 billion photos are taken every day worldwide — roughly 16,000 photos per second. More photos are taken every two minutes today than were taken in all of the 1800s combined.",
    source: "https://focus.mylio.com/tech-today/how-many-photos-are-taken-per-day",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-23",
    questionNumber: 54,
    question: "How many Google searches happen every day, worldwide?",
    answer: 8500000000,
    unit: "searches",
    explanation:
      "Google processes over 8.5 billion searches per day — roughly 99,000 per second. That's more searches every day than there are people on Earth.",
    source: "https://blog.hubspot.com/marketing/google-search-statistics",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-24",
    questionNumber: 55,
    question: "How many emails are sent worldwide every single day?",
    answer: 333000000000,
    unit: "emails",
    explanation:
      "Over 333 billion emails are sent globally every day. About 45% are spam. That's roughly 40 emails per person on Earth, every single day.",
    source: "https://www.statista.com/statistics/456500/daily-number-of-e-mails-worldwide/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-25",
    questionNumber: 56,
    question: "How many songs are in Spotify's music library?",
    answer: 100000000,
    unit: "songs",
    explanation:
      "Spotify's library has over 100 million tracks. About 100,000 new songs are uploaded every day. Listening to them all non-stop at 3 minutes each would take over 570 years.",
    source: "https://newsroom.spotify.com/company-info/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-26",
    questionNumber: 57,
    question: "How many hours of video are uploaded to YouTube every minute?",
    answer: 500,
    unit: "hours",
    explanation:
      "Over 500 hours of video are uploaded to YouTube every single minute. That's 720,000 hours of new content per day — more video than you could watch in multiple lifetimes.",
    source: "https://blog.youtube/press/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-27",
    questionNumber: 58,
    question: "How many websites exist on the internet?",
    answer: 2000000000,
    unit: "websites",
    explanation:
      "There are roughly 2 billion registered websites, though fewer than 200 million are actively maintained. The first website was published by Tim Berners-Lee in 1991 — and it's still online.",
    source: "https://www.internetlivestats.com/total-number-of-websites/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-28",
    questionNumber: 59,
    question: "How many packages does Amazon ship per day worldwide?",
    answer: 35000000,
    unit: "packages",
    explanation:
      "Amazon ships roughly 35 million packages per day. During peak holiday seasons, that number can exceed 50 million. That's more than one package per second, around the clock.",
    source: "https://www.statista.com/statistics/561768/amazon-number-of-packages-shipped/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-04-29",
    questionNumber: 60,
    question: "How many books are published in the United States every year?",
    answer: 1000000,
    unit: "books",
    explanation:
      "About 1 million new books are published in the US every year, including self-published titles. You would need to read roughly 2,740 books per day to keep up — without sleeping.",
    source: "https://www.bowker.com/news/2019/New-Book-Production-Slows-in-2018.html",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-04-30",
    questionNumber: 61,
    question: "How many McDonald's restaurants are there worldwide?",
    answer: 40000,
    unit: "locations",
    explanation:
      "There are about 40,000 McDonald's locations across 100+ countries. Together they serve roughly 69 million customers per day — that's about 1% of the world's population, daily.",
    source: "https://corporate.mcdonalds.com/corpmcd/about-us/our-history.html",
    category: "SCALE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-05-01",
    questionNumber: 62,
    question: "How many cups of coffee are consumed worldwide every single day?",
    answer: 2250000000,
    unit: "cups",
    explanation:
      "About 2.25 billion cups of coffee are consumed globally every day — roughly 400 billion per year. Coffee is the most traded tropical commodity in the world, second only to oil overall.",
    source: "https://www.ico.org/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-02",
    questionNumber: 63,
    question: "How many tweets are sent on X (Twitter) every day?",
    answer: 500000000,
    unit: "tweets",
    explanation:
      "Around 500 million tweets are sent daily on X — about 6,000 per second. If you tried to read every tweet posted in a single day, at one per second it would take about 15 years.",
    source: "https://www.internetlivestats.com/twitter-statistics/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-03",
    questionNumber: 64,
    question: "How many text messages are sent worldwide every day?",
    answer: 23000000000,
    unit: "messages",
    explanation:
      "About 23 billion text messages are sent every day around the world. That's roughly 267,000 messages per second — and this figure has grown tenfold over the past decade.",
    source: "https://www.statista.com/statistics/264810/number-of-monthly-active-facebook-users-worldwide/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-04",
    questionNumber: 65,
    question: "How many apps are in the Apple App Store?",
    answer: 1800000,
    unit: "apps",
    explanation:
      "The Apple App Store contains about 1.8 million apps. If you downloaded one new app every day, it would take nearly 5,000 years to download them all. About 60% of apps have never been downloaded.",
    source: "https://www.statista.com/statistics/268251/number-of-apps-in-the-itunes-app-store-since-2008/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-05",
    questionNumber: 66,
    question: "How many transistors are on a modern high-end CPU processor chip?",
    answer: 50000000000,
    unit: "transistors",
    explanation:
      "Modern CPUs contain roughly 50 billion transistors on a chip the size of your thumbnail. In 1971, the first commercial microprocessor had just 2,300 transistors — that's a 20-million-fold increase in 50 years.",
    source: "https://ourworldindata.org/transistors",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-06",
    questionNumber: 67,
    question: "How many cars are there in the world?",
    answer: 1400000000,
    unit: "cars",
    explanation:
      "There are approximately 1.4 billion cars in the world. That's roughly one car for every 6 people on Earth. If you lined them all up bumper-to-bumper, the line would stretch to the Moon and back over 600 times.",
    source: "https://www.statista.com/statistics/281134/number-of-vehicles-in-use-worldwide/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-07",
    questionNumber: 68,
    question: "How many pieces of plastic are estimated to be floating in Earth's oceans?",
    answer: 5000000000000,
    unit: "pieces",
    explanation:
      "Scientists estimate there are roughly 5 trillion pieces of plastic in the world's oceans. That's about 700 pieces for every person on Earth, and the number grows by millions of tons every year.",
    source: "https://www.ocean.si.edu/ocean-life/fish/ocean-plastic",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-08",
    questionNumber: 69,
    question: "How many credit card transactions happen worldwide every day?",
    answer: 500000000,
    unit: "transactions",
    explanation:
      "About 500 million credit and debit card transactions take place globally every day. Visa alone processes more than 200 million of those. That's roughly 6,000 swipes per second.",
    source: "https://www.visa.com/about-visa/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-09",
    questionNumber: 70,
    question: "How many hot dogs are consumed in the United States every year?",
    answer: 20000000000,
    unit: "hot dogs",
    explanation:
      "Americans eat about 20 billion hot dogs per year — about 70 per person. On July 4th alone, Americans consume roughly 150 million hot dogs, making it the biggest hot dog day of the year.",
    source: "https://www.hot-dog.org/culture/hot-dog-facts",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-10",
    questionNumber: 71,
    question: "How many LEGO bricks are produced every year?",
    answer: 36000000000,
    unit: "bricks",
    explanation:
      "LEGO produces about 36 billion bricks per year — roughly 4 bricks for every person on Earth, every single year. There are estimated to be over 400 billion LEGO bricks in existence.",
    source: "https://www.lego.com/en-us/aboutus/lego-group/the-lego-group-history/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-11",
    questionNumber: 72,
    question: "How many Rubik's Cubes have been sold since it was invented?",
    answer: 500000000,
    unit: "cubes",
    explanation:
      "Over 500 million Rubik's Cubes have been sold since 1974 — making it the best-selling puzzle toy of all time. The world record for solving one is 3.13 seconds.",
    source: "https://www.rubiks.com/en-gb/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-12",
    questionNumber: 73,
    question: "How many languages are actively spoken in the world today?",
    answer: 7000,
    unit: "languages",
    explanation:
      "There are roughly 7,000 languages spoken in the world today, though about 40% are endangered. Papua New Guinea alone has over 800 languages — the most linguistic diversity of any country.",
    source: "https://www.ethnologue.com/",
    category: "SCALE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-05-13",
    questionNumber: 74,
    question: "How many pieces of mail does the US Postal Service deliver per day?",
    answer: 421000000,
    unit: "pieces of mail",
    explanation:
      "The USPS delivers about 421 million pieces of mail per day, including letters, packages, and flats. Despite digital communication, it remains one of the largest postal networks in the world.",
    source: "https://about.usps.com/what/performance/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-14",
    questionNumber: 75,
    question: "How many TikTok videos are viewed every day?",
    answer: 1000000000,
    unit: "videos",
    explanation:
      "TikTok users watch roughly 1 billion videos per day — about 12,000 videos every second. If every video were 30 seconds long, that's over 30 billion seconds of content watched daily.",
    source: "https://newsroom.tiktok.com/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-15",
    questionNumber: 76,
    question: "How many satellites are currently orbiting Earth?",
    answer: 7500,
    unit: "satellites",
    explanation:
      "There are roughly 7,500 active satellites in orbit around Earth. That number has exploded since 2019 due to SpaceX Starlink, which accounts for more than half of all active satellites.",
    source: "https://www.ucsusa.org/resources/satellite-database",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-16",
    questionNumber: 77,
    question: "How many Starbucks locations are there worldwide?",
    answer: 36000,
    unit: "locations",
    explanation:
      "Starbucks operates about 36,000 locations in 80+ countries. If you visited one new Starbucks every day, it would take you about 99 years to visit them all.",
    source: "https://investor.starbucks.com/",
    category: "SCALE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-05-17",
    questionNumber: 78,
    question: "How many dollars does Apple earn in revenue every year?",
    answer: 383000000000,
    unit: "dollars",
    explanation:
      "Apple's annual revenue is roughly $383 billion — about $12,000 per second. Its market value has at times exceeded $3 trillion, making it briefly worth more than the GDP of France.",
    source: "https://www.apple.com/newsroom/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-18",
    questionNumber: 79,
    question: "How much does the US spend on pet food every year, in dollars?",
    answer: 50000000000,
    unit: "dollars",
    explanation:
      "Americans spend over $50 billion on pet food annually — more than the entire GDP of many small countries. Total US pet spending including vet care and supplies exceeds $130 billion per year.",
    source: "https://www.americanpetsproducts.org/press_industry_trends.asp",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-19",
    questionNumber: 80,
    question: "How much did it cost to build the International Space Station, in dollars?",
    answer: 150000000000,
    unit: "dollars",
    explanation:
      "The ISS cost approximately $150 billion to build and maintain — making it the most expensive structure ever constructed. It's also the size of a football field and orbits Earth at 17,500 mph.",
    source: "https://www.nasa.gov/international-space-station/facts-and-figures/",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-20",
    questionNumber: 81,
    question: "How many cups of tea are drunk worldwide every day?",
    answer: 3000000000,
    unit: "cups",
    explanation:
      "About 3 billion cups of tea are consumed globally every day. Tea is the most widely consumed beverage in the world after water. China and India together account for nearly half of all production.",
    source: "https://www.fao.org/3/i4480e/i4480e.pdf",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-21",
    questionNumber: 82,
    question: "What is NASA's annual budget in dollars?",
    answer: 25000000000,
    unit: "dollars",
    explanation:
      "NASA's annual budget is about $25 billion — roughly 0.5% of the US federal budget. For every dollar the US government spends, NASA gets less than one cent.",
    source: "https://www.nasa.gov/news-release/nasa-budget-information/",
    category: "SCALE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-22",
    questionNumber: 83,
    question: "How many billions of dollars does the global video game industry make per year?",
    answer: 200000000000,
    unit: "dollars",
    explanation:
      "The global video game industry generates roughly $200 billion annually — more than the film and music industries combined. Mobile gaming now accounts for nearly half of all gaming revenue.",
    source: "https://www.newzoo.com/resources/blog/the-global-games-market-revenues-2022",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-23",
    questionNumber: 84,
    question: "How many barrels of oil does the world consume every day?",
    answer: 100000000,
    unit: "barrels",
    explanation:
      "The world consumes roughly 100 million barrels of oil per day. One barrel equals 42 gallons of crude oil. That's about 4.2 billion gallons of oil burned globally, every single day.",
    source: "https://www.eia.gov/energyexplained/oil-and-petroleum-products/use-of-oil.php",
    category: "SCALE" as Category,
    difficulty: "hard" as Difficulty,
  },

  // ============================================================
  // SPACE (22)
  // ============================================================
  {
    date: "2026-05-24",
    questionNumber: 85,
    question: "How far away is the Moon in miles?",
    answer: 238900,
    unit: "miles",
    explanation:
      "The Moon is about 238,900 miles from Earth. Remarkably, you could fit all 7 other planets in our solar system side by side in that gap — with room to spare.",
    source: "https://moon.nasa.gov/about/in-depth/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-25",
    questionNumber: 86,
    question: "How many Earths could fit inside the Sun?",
    answer: 1300000,
    unit: "Earths",
    explanation:
      "About 1.3 million Earths could fit inside the Sun. The Sun contains over 99.86% of all mass in our entire solar system — everything else is less than 0.2% of the total.",
    source: "https://solarsystem.nasa.gov/solar-system/sun/overview/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-26",
    questionNumber: 87,
    question: "How many stars are estimated to be in the Milky Way galaxy?",
    answer: 200000000000,
    unit: "stars",
    explanation:
      "The Milky Way contains an estimated 100–400 billion stars, with 200 billion as the most commonly cited figure. And the observable universe contains roughly 2 trillion galaxies.",
    source: "https://asd.gsfc.nasa.gov/blueshift/index.php/2015/07/22/how-many-stars-in-the-milky-way/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-27",
    questionNumber: 88,
    question: "How many minutes does it take sunlight to travel from the Sun to Earth?",
    answer: 8.3,
    unit: "minutes",
    explanation:
      "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth. This means you're always seeing the Sun as it was 8 minutes ago — we could never see it disappear in real time.",
    source: "https://solarsystem.nasa.gov/solar-system/sun/overview/",
    category: "SPACE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-05-28",
    questionNumber: 89,
    question: "How fast does the International Space Station travel, in miles per hour?",
    answer: 17500,
    unit: "mph",
    explanation:
      "The ISS travels at about 17,500 mph — fast enough to circle Earth in 92 minutes. At that speed, you could fly from New York to Los Angeles in under 10 minutes.",
    source: "https://www.nasa.gov/international-space-station/facts-and-figures/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-29",
    questionNumber: 90,
    question: "How many light-years away is the observable edge of the universe?",
    answer: 46500000000,
    unit: "light-years",
    explanation:
      "The observable universe extends roughly 46.5 billion light-years in every direction. Even though the universe is only 13.8 billion years old, it expanded faster than the speed of light in its early stages.",
    source: "https://www.nasa.gov/universe/overview/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-05-30",
    questionNumber: 91,
    question: "How many confirmed moons does Saturn have?",
    answer: 146,
    unit: "moons",
    explanation:
      "Saturn has 146 confirmed moons as of 2023, making it the most moon-rich planet in our solar system. Its largest moon, Titan, is bigger than the planet Mercury and has a thick atmosphere.",
    source: "https://solarsystem.nasa.gov/moons/saturn-moons/overview/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-05-31",
    questionNumber: 92,
    question: "What is the surface temperature of the Sun in degrees Fahrenheit?",
    answer: 9940,
    unit: "°F",
    explanation:
      "The Sun's surface temperature is about 9,940°F (5,500°C). Strangely, its outer atmosphere — the corona — reaches over 1 million°F. Why the corona is hotter than the surface remains an unsolved mystery.",
    source: "https://solarsystem.nasa.gov/solar-system/sun/in-depth/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-01",
    questionNumber: 93,
    question: "How fast does light travel, in miles per second?",
    answer: 186000,
    unit: "miles per second",
    explanation:
      "Light travels at 186,000 miles per second — fast enough to circle Earth 7.5 times in a single second. Nothing in the known universe can travel faster.",
    source: "https://www.scientificamerican.com/article/what-is-the-speed-of-light/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-02",
    questionNumber: 94,
    question: "What is the diameter of Earth in miles?",
    answer: 7926,
    unit: "miles",
    explanation:
      "Earth's diameter is about 7,926 miles. For context, a commercial flight around the equator (24,901 miles) would take about 40 hours — but flying through Earth would only take about 13 hours at the same speed.",
    source: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-03",
    questionNumber: 95,
    question: "How many light-years wide is the Milky Way galaxy?",
    answer: 100000,
    unit: "light-years",
    explanation:
      "The Milky Way is about 100,000 light-years across. Even at the speed of light, crossing our home galaxy would take 100,000 years. Our solar system is roughly 26,000 light-years from the center.",
    source: "https://www.nasa.gov/image-detail/milky-way-galaxy/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-04",
    questionNumber: 96,
    question: "What is the temperature of outer space in degrees Fahrenheit?",
    answer: -455,
    unit: "°F",
    explanation:
      "The temperature of empty space is about -455°F (-270°C), just barely above absolute zero. This is the temperature of the cosmic microwave background radiation left over from the Big Bang.",
    source: "https://science.nasa.gov/universe/overview/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-05",
    questionNumber: 97,
    question: "How fast is the Voyager 1 spacecraft traveling, in miles per hour?",
    answer: 38000,
    unit: "mph",
    explanation:
      "Voyager 1, the most distant human-made object, travels at about 38,000 mph. Launched in 1977, it's now over 14 billion miles from Earth — and it still calls home.",
    source: "https://voyager.jpl.nasa.gov/mission/status/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-06",
    questionNumber: 98,
    question: "How many miles away is Mars at its closest approach to Earth?",
    answer: 38600000,
    unit: "miles",
    explanation:
      "At its closest point (opposition), Mars is about 38.6 million miles from Earth. At its farthest, it's over 250 million miles away. A one-way trip at spacecraft speeds takes 7–9 months.",
    source: "https://solarsystem.nasa.gov/planets/mars/overview/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-07",
    questionNumber: 99,
    question: "How many confirmed exoplanets (planets outside our solar system) have been discovered?",
    answer: 5600,
    unit: "exoplanets",
    explanation:
      "Over 5,600 exoplanets have been confirmed as of recent data, with thousands more candidates awaiting verification. Many are in the 'habitable zone' of their stars — potentially capable of having liquid water.",
    source: "https://exoplanets.nasa.gov/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-08",
    questionNumber: 100,
    question: "What is the diameter of Jupiter in miles?",
    answer: 88800,
    unit: "miles",
    explanation:
      "Jupiter's equatorial diameter is about 88,800 miles — more than 11 times wider than Earth. All other planets in our solar system could fit inside Jupiter with room to spare.",
    source: "https://solarsystem.nasa.gov/planets/jupiter/in-depth/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-09",
    questionNumber: 101,
    question: "How many years until our Sun will run out of hydrogen and become a red giant?",
    answer: 5000000000,
    unit: "years",
    explanation:
      "Our Sun has about 5 billion years of hydrogen fuel left. When it runs out, it will expand into a red giant large enough to swallow Mercury, Venus, and possibly Earth.",
    source: "https://solarsystem.nasa.gov/solar-system/sun/in-depth/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-10",
    questionNumber: 102,
    question: "How many years does it take Pluto to orbit the Sun once?",
    answer: 248,
    unit: "years",
    explanation:
      "Pluto takes 248 Earth years to complete one orbit around the Sun. Pluto was discovered in 1930, and it hasn't even completed one orbit since humans first spotted it.",
    source: "https://solarsystem.nasa.gov/planets/dwarf-planets/pluto/in-depth/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-11",
    questionNumber: 103,
    question: "How many craters are on the Moon's surface?",
    answer: 300000,
    unit: "craters",
    explanation:
      "The Moon has roughly 300,000 impact craters larger than about 1 km in diameter. Because the Moon has no atmosphere or tectonic activity, these craters are preserved essentially forever.",
    source: "https://www.lpi.usra.edu/lunar/surface/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-12",
    questionNumber: 104,
    question: "What is the temperature of the Moon's surface during the day in degrees Fahrenheit?",
    answer: 260,
    unit: "°F",
    explanation:
      "The Moon's surface heats up to about 260°F (127°C) during the day, and plunges to -280°F at night — a 540-degree swing. Without an atmosphere to trap heat, there's nothing to even out the extremes.",
    source: "https://moon.nasa.gov/about/in-depth/",
    category: "SPACE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-13",
    questionNumber: 105,
    question: "How many miles away from the Sun is Neptune?",
    answer: 2800000000,
    unit: "miles",
    explanation:
      "Neptune orbits the Sun at an average distance of about 2.8 billion miles. Sunlight takes roughly 4 hours to reach Neptune — compared to only 8 minutes to reach Earth.",
    source: "https://solarsystem.nasa.gov/planets/neptune/in-depth/",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-14",
    questionNumber: 106,
    question: "How many miles per hour does Earth travel around the Sun?",
    answer: 67000,
    unit: "mph",
    explanation:
      "Earth orbits the Sun at about 67,000 mph (18.5 miles per second). You're hurtling through space right now at nearly 20 times the speed of a bullet — without feeling a thing.",
    source: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html",
    category: "SPACE" as Category,
    difficulty: "hard" as Difficulty,
  },

  // ============================================================
  // NATURE (26)
  // ============================================================
  {
    date: "2026-06-15",
    questionNumber: 107,
    question: "How many times does lightning strike Earth every day?",
    answer: 8000000,
    unit: "strikes",
    explanation:
      "Lightning strikes Earth about 8 million times per day — roughly 100 strikes per second. About 70% occur in the tropics, and a single bolt can heat the surrounding air to 30,000°C — five times hotter than the Sun's surface.",
    source: "https://www.nasa.gov/mission/lightning-imaging-sensor-lis-on-the-iss/",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-16",
    questionNumber: 108,
    question: "How many trees are on Earth?",
    answer: 3000000000000,
    unit: "trees",
    explanation:
      "There are roughly 3 trillion trees on Earth — about 400 trees for every person. Despite this, we're losing about 10 billion trees per year to deforestation, a number that exceeds replanting by a wide margin.",
    source: "https://www.nature.com/articles/nature14967",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-17",
    questionNumber: 109,
    question: "How deep is the deepest point in the ocean, in feet?",
    answer: 36161,
    unit: "feet",
    explanation:
      "The Mariana Trench's Challenger Deep reaches 36,161 feet — nearly 7 miles. If you dropped Mount Everest into it, the peak would still be over a mile underwater.",
    source: "https://oceanservice.noaa.gov/facts/oceandepth.html",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-18",
    questionNumber: 110,
    question: "How many insect species have scientists identified on Earth?",
    answer: 900000,
    unit: "species",
    explanation:
      "Scientists have identified about 900,000 insect species, but estimate there may be 5–10 million total. Insects make up about 80% of all known animal species on Earth.",
    source: "https://www.si.edu/spotlight/buginfo/bugnos",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-19",
    questionNumber: 111,
    question: "How old is Methuselah, the world's oldest known living tree, in years?",
    answer: 4856,
    unit: "years",
    explanation:
      "Methuselah, a Great Basin bristlecone pine in California's White Mountains, is over 4,856 years old. It was already ancient when the Egyptian pyramids were being built. Its exact location is kept secret to protect it.",
    source: "https://www.fs.usda.gov/detail/inyo/home/?cid=stelprdb5129900",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-20",
    questionNumber: 112,
    question: "How many species of living things are estimated to exist on Earth?",
    answer: 8700000,
    unit: "species",
    explanation:
      "Scientists estimate there are about 8.7 million species on Earth — but only about 1.2 million have been formally described. We're still discovering thousands of new species every year.",
    source: "https://www.nature.com/articles/ncomms1213",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-21",
    questionNumber: 113,
    question: "How many miles long is the Amazon River?",
    answer: 3976,
    unit: "miles",
    explanation:
      "The Amazon River stretches roughly 3,976 miles — second only to the Nile in length. It discharges about 20% of all fresh water that flows into the world's oceans and contains more fish species than the entire Atlantic Ocean.",
    source: "https://www.worldwildlife.org/places/amazon",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-22",
    questionNumber: 114,
    question: "How tall is Mount Everest in feet?",
    answer: 29032,
    unit: "feet",
    explanation:
      "Mount Everest stands 29,032 feet (8,849 meters) above sea level — the highest point on Earth. Interestingly, due to Earth's equatorial bulge, the mountain Chimborazo in Ecuador is actually furthest from Earth's center.",
    source: "https://www.nationalgeographic.com/adventure/article/mount-everest",
    category: "NATURE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-06-23",
    questionNumber: 115,
    question: "How fast can a cheetah run at top speed, in miles per hour?",
    answer: 70,
    unit: "mph",
    explanation:
      "Cheetahs can reach top speeds of about 70 mph — but only for short bursts of 20–30 seconds. They can go from 0 to 60 mph in just 3 seconds, which is faster than most sports cars.",
    source: "https://www.nationalgeographic.com/animals/mammals/facts/cheetah",
    category: "NATURE" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-06-24",
    questionNumber: 116,
    question: "How many species of ants have been discovered worldwide?",
    answer: 20000,
    unit: "species",
    explanation:
      "About 20,000 ant species have been identified worldwide. Ants collectively outweigh all wild birds and mammals combined. A single army ant colony can contain over 700,000 individuals.",
    source: "https://www.antark.net/ant-facts/",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-25",
    questionNumber: 117,
    question: "How thick is the Earth's crust on average, in miles?",
    answer: 25,
    unit: "miles",
    explanation:
      "Earth's crust averages about 25 miles thick — but ranges from as little as 3 miles under ocean floors to up to 46 miles under mountain ranges. Compared to Earth's total radius of 3,959 miles, it's thinner than an eggshell by ratio.",
    source: "https://www.usgs.gov/faqs/what-earths-crust",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-26",
    questionNumber: 118,
    question: "What is the estimated temperature of Earth's inner core in degrees Fahrenheit?",
    answer: 10800,
    unit: "°F",
    explanation:
      "Earth's inner core is estimated to be about 10,800°F (6,000°C) — about as hot as the surface of the Sun. Despite this extreme heat, the intense pressure keeps it solid iron.",
    source: "https://www.usgs.gov/faqs/how-hot-is-earths-core",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-27",
    questionNumber: 119,
    question: "How long is the Great Barrier Reef in miles?",
    answer: 1429,
    unit: "miles",
    explanation:
      "The Great Barrier Reef stretches about 1,429 miles along Australia's northeast coast — roughly the distance from Miami to Chicago. It's the world's largest living structure, visible from space.",
    source: "https://www.gbrmpa.gov.au/the-reef/about-the-reef",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-28",
    questionNumber: 120,
    question: "How many earthquakes occur on Earth every year?",
    answer: 500000,
    unit: "earthquakes",
    explanation:
      "About 500,000 earthquakes occur worldwide every year — roughly 1,370 per day. Most are too small to be felt. About 100,000 are noticeable, and about 100 cause serious damage.",
    source: "https://www.usgs.gov/programs/earthquake-hazards/earthquakes-faq",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-06-29",
    questionNumber: 121,
    question: "What is the wind speed of the strongest tornado ever recorded, in miles per hour?",
    answer: 301,
    unit: "mph",
    explanation:
      "The highest tornado wind speed ever recorded was 301 mph in the 1999 Bridge Creek-Moore tornado in Oklahoma. Most tornadoes produce winds under 110 mph, but EF5 events are devastating.",
    source: "https://www.noaa.gov/education/resource-collections/weather-atmosphere/tornadoes",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-06-30",
    questionNumber: 122,
    question: "How old is the Earth in years?",
    answer: 4500000000,
    unit: "years",
    explanation:
      "Earth is approximately 4.5 billion years old, determined through radiometric dating of meteorites and lunar rocks. The oldest rocks found on Earth's surface are about 4 billion years old.",
    source: "https://www.usgs.gov/faqs/how-old-earth",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-01",
    questionNumber: 123,
    question: "How many active volcanoes are there on Earth?",
    answer: 1500,
    unit: "volcanoes",
    explanation:
      "There are about 1,500 active volcanoes on Earth — around 500 have erupted in recorded history. About 50–70 volcanoes erupt in any given year, though most are minor events.",
    source: "https://www.usgs.gov/programs/VHP",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-02",
    questionNumber: 124,
    question: "How deep is Lake Baikal, the world's deepest lake, in feet?",
    answer: 5387,
    unit: "feet",
    explanation:
      "Lake Baikal in Russia is 5,387 feet deep — over a mile. It holds about 20% of the world's unfrozen surface fresh water — more than all five Great Lakes combined.",
    source: "https://www.nationalgeographic.com/environment/article/lake-baikal",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-03",
    questionNumber: 125,
    question: "How many species of birds have been identified on Earth?",
    answer: 10000,
    unit: "species",
    explanation:
      "Scientists have identified about 10,000 bird species. About 40% of bird species are in decline. A single domestic cat kills an estimated 1–4 billion birds in the US alone each year.",
    source: "https://www.allaboutbirds.org/",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-04",
    questionNumber: 126,
    question: "How tall was the largest wave ever recorded, in feet?",
    answer: 1720,
    unit: "feet",
    explanation:
      "In 1958, an earthquake-triggered megatsunami in Lituya Bay, Alaska, sent a wave runup of 1,720 feet up the surrounding slopes — taller than the Empire State Building. Two fishing boats were lifted over the treeline.",
    source: "https://oceanservice.noaa.gov/hazards/tsunamis/",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-05",
    questionNumber: 127,
    question: "How many square miles does the Amazon rainforest cover?",
    answer: 2100000,
    unit: "square miles",
    explanation:
      "The Amazon rainforest covers about 2.1 million square miles — roughly the size of the contiguous United States. It produces about 6% of Earth's oxygen and houses 10% of all known species.",
    source: "https://www.worldwildlife.org/places/amazon",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-06",
    questionNumber: 128,
    question: "How many known spider species have been identified worldwide?",
    answer: 50000,
    unit: "species",
    explanation:
      "About 50,000 spider species have been identified. Scientists estimate there are roughly one million individual spiders per acre of land in most habitats. You're statistically never more than a few feet from a spider.",
    source: "https://www.worldspiders.org/",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-07",
    questionNumber: 129,
    question: "What were the peak sustained wind speeds of Hurricane Patricia, the strongest hurricane on record, in mph?",
    answer: 215,
    unit: "mph",
    explanation:
      "Hurricane Patricia (2015) peaked at sustained winds of 215 mph — the strongest ever recorded in the Western Hemisphere. It rapidly intensified from a tropical storm to Category 5 in just 24 hours.",
    source: "https://www.nhc.noaa.gov/data/tcr/EP202015_Patricia.pdf",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-08",
    questionNumber: 130,
    question: "How old is the oldest seafloor on Earth, in millions of years?",
    answer: 200,
    unit: "million years",
    explanation:
      "The oldest oceanic crust on Earth is about 200 million years old, found in the western Pacific. Continental crust can be over 4 billion years old — ocean floors are constantly recycled by tectonic subduction.",
    source: "https://www.usgs.gov/programs/earthquake-hazards/science/plate-tectonics",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-09",
    questionNumber: 131,
    question: "How many individual fish are estimated to live in Earth's oceans?",
    answer: 1000000000000,
    unit: "fish",
    explanation:
      "Scientists estimate roughly 1 trillion fish live in the world's oceans. The total weight of all ocean fish is estimated at about 800–2,000 million tons. Yet humans catch about 80 million tons per year.",
    source: "https://www.fishcount.org.uk/",
    category: "NATURE" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-10",
    questionNumber: 132,
    question: "What is the average depth of the world's oceans in feet?",
    answer: 12100,
    unit: "feet",
    explanation:
      "The average depth of the world's oceans is about 12,100 feet — roughly 2.3 miles. The oceans cover about 71% of Earth's surface, yet more than 80% of the ocean floor remains unmapped.",
    source: "https://oceanservice.noaa.gov/facts/oceandepth.html",
    category: "NATURE" as Category,
    difficulty: "medium" as Difficulty,
  },

  // ============================================================
  // HISTORY (22)
  // ============================================================
  {
    date: "2026-07-11",
    questionNumber: 133,
    question: "How many years ago were the Egyptian pyramids built?",
    answer: 4500,
    unit: "years ago",
    explanation:
      "The Great Pyramid of Giza was built around 2560 BC — roughly 4,500 years ago. Cleopatra actually lived closer in time to us than to the building of the pyramids.",
    source: "https://www.britannica.com/topic/Pyramids-of-Giza",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-12",
    questionNumber: 134,
    question: "How many total deaths (military and civilian) did World War I cause?",
    answer: 20000000,
    unit: "deaths",
    explanation:
      "World War I caused approximately 20 million deaths — both military and civilian. It was followed three years later by the 1918 Spanish flu pandemic, which killed at least 50 million more.",
    source: "https://www.britannica.com/event/World-War-I",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-13",
    questionNumber: 135,
    question: "How many years did the Cold War last?",
    answer: 44,
    unit: "years",
    explanation:
      "The Cold War lasted from 1947 (Truman Doctrine) to 1991 (dissolution of the Soviet Union) — 44 years. During this period, both superpowers built enough nuclear warheads to destroy civilization multiple times over.",
    source: "https://www.history.com/topics/cold-war/cold-war-history",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-07-14",
    questionNumber: 136,
    question: "How many member nations does the United Nations have?",
    answer: 193,
    unit: "countries",
    explanation:
      "The United Nations has 193 member states — nearly every country on Earth. Notable non-members include Vatican City and Palestine (both have observer status). The UN was founded in 1945 with just 51 members.",
    source: "https://www.un.org/en/member-states/",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-07-15",
    questionNumber: 137,
    question: "How many years did slavery exist in the United States before abolition?",
    answer: 246,
    unit: "years",
    explanation:
      "Slavery existed in what became the United States from 1619 (first enslaved Africans brought to Virginia) until the 13th Amendment in 1865 — 246 years. The US is younger as a country (250 years) than slavery lasted within it.",
    source: "https://www.history.com/topics/american-civil-war/13th-amendment",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-16",
    questionNumber: 138,
    question: "How many presidents has the United States had?",
    answer: 47,
    unit: "presidents",
    explanation:
      "The United States has had 47 presidents as of 2025. Grover Cleveland is counted twice (22nd and 24th president) as the only person to serve non-consecutive terms, so 46 people have held the office.",
    source: "https://www.whitehouse.gov/about-the-white-house/presidents/",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-07-17",
    questionNumber: 139,
    question: "How many years ago did Gutenberg invent the printing press?",
    answer: 576,
    unit: "years ago",
    explanation:
      "Johannes Gutenberg invented the movable-type printing press around 1450 — about 576 years ago. Within 50 years, an estimated 8 million books had been printed — more than all of European scribes had produced in the preceding 1,000 years.",
    source: "https://www.britannica.com/biography/Johannes-Gutenberg",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-18",
    questionNumber: 140,
    question: "How many miles of trenches were dug during World War I?",
    answer: 25000,
    unit: "miles",
    explanation:
      "An estimated 25,000 miles of trenches were dug during WWI — enough to circle the Earth once. Soldiers on the Western Front sometimes lived in these trenches for months, just hundreds of yards from the enemy.",
    source: "https://www.history.com/topics/world-war-i/trench-warfare",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-19",
    questionNumber: 141,
    question: "How many people died from the Black Death in the 14th century?",
    answer: 75000000,
    unit: "deaths",
    explanation:
      "The Black Death killed approximately 75 million people worldwide — wiping out 30–50% of Europe's entire population. Some regions lost 60–70% of their population in just a few years.",
    source: "https://www.history.com/topics/middle-ages/black-death",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-20",
    questionNumber: 142,
    question: "How many years ago was the Magna Carta signed?",
    answer: 811,
    unit: "years ago",
    explanation:
      "The Magna Carta was signed in 1215 — about 811 years ago. It was the first document to establish that the king was subject to the rule of law, a principle that underlies modern constitutional democracies.",
    source: "https://www.bl.uk/magna-carta",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-21",
    questionNumber: 143,
    question: "How many years did the Hundred Years' War between England and France actually last?",
    answer: 116,
    unit: "years",
    explanation:
      "The Hundred Years' War lasted from 1337 to 1453 — a full 116 years, not 100. It involved multiple generations of soldiers and kings, and Joan of Arc famously turned the tide for France near the end.",
    source: "https://www.britannica.com/event/Hundred-Years-War",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-07-22",
    questionNumber: 144,
    question: "How many years passed between Cleopatra's death and the first iPhone?",
    answer: 2037,
    unit: "years",
    explanation:
      "Cleopatra died in 30 BC, and the iPhone launched in 2007 — 2,037 years apart. Yet Cleopatra lived closer in time to the iPhone than to the construction of the Great Pyramid (which was 2,530 years before her birth).",
    source: "https://www.britannica.com/biography/Cleopatra-queen-of-Egypt",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-23",
    questionNumber: 145,
    question: "How many years ago were the first Olympic Games held?",
    answer: 2802,
    unit: "years ago",
    explanation:
      "The first Olympic Games were held in Olympia, Greece in 776 BC — about 2,802 years ago. They were held every 4 years for over 1,000 years until the Roman Emperor Theodosius I abolished them in 393 AD.",
    source: "https://www.olympic.org/ancient-olympic-games",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-24",
    questionNumber: 146,
    question: "How many people lived in the Roman Empire at its peak?",
    answer: 70000000,
    unit: "people",
    explanation:
      "The Roman Empire had a population of roughly 70 million people at its peak under Emperor Trajan (c. 117 AD) — about 21% of the entire world's population at the time.",
    source: "https://www.britannica.com/place/ancient-Rome",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-25",
    questionNumber: 147,
    question: "How many years ago was the US Declaration of Independence signed?",
    answer: 250,
    unit: "years ago",
    explanation:
      "The Declaration of Independence was signed in 1776 — 250 years ago as of 2026. The US is remarkably young: when it was founded, the pyramids were already 4,250 years old.",
    source: "https://www.archives.gov/founding-docs/declaration",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-07-26",
    questionNumber: 148,
    question: "How many nations participated in the first modern Olympic Games in 1896?",
    answer: 14,
    unit: "nations",
    explanation:
      "Only 14 nations sent athletes to the first modern Olympics in Athens in 1896, with 241 male athletes competing in 43 events. By comparison, the 2024 Paris Olympics had 206 nations and 10,500 athletes.",
    source: "https://www.olympic.org/athens-1896",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-07-27",
    questionNumber: 149,
    question: "How many days long was the longest siege in history — the Ottoman Siege of Candia in Crete?",
    answer: 7665,
    unit: "days",
    explanation:
      "The Ottoman siege of Candia (modern Heraklion) lasted from 1648 to 1669 — about 7,665 days, or 21 years. When the city finally fell, it was the end of Venetian control of Crete after 450 years.",
    source: "https://www.britannica.com/event/Siege-of-Candia",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-28",
    questionNumber: 150,
    question: "How many years did the Ming Dynasty rule China?",
    answer: 276,
    unit: "years",
    explanation:
      "The Ming Dynasty ruled China from 1368 to 1644 — 276 years. During this period, China built most of the Great Wall as we know it today and sent enormous fleets as far as East Africa.",
    source: "https://www.britannica.com/topic/Ming-dynasty",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-29",
    questionNumber: 151,
    question: "How many soldiers fought in the Battle of the Somme in 1916?",
    answer: 3000000,
    unit: "soldiers",
    explanation:
      "Roughly 3 million men fought at the Battle of the Somme. On the first day alone — July 1, 1916 — Britain suffered 57,470 casualties, the bloodiest single day in British military history.",
    source: "https://www.iwm.org.uk/history/the-battle-of-the-somme",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-30",
    questionNumber: 152,
    question: "How many years did the British Empire span, from its founding to decolonization?",
    answer: 414,
    unit: "years",
    explanation:
      "The British Empire lasted roughly 414 years — from the establishment of colonies in the 1580s to the handover of Hong Kong in 1997. At its peak in 1920, it covered about 24% of Earth's land surface.",
    source: "https://www.britannica.com/place/British-Empire",
    category: "HISTORY" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-07-31",
    questionNumber: 153,
    question: "How many years ago was the first Moon landing?",
    answer: 57,
    unit: "years ago",
    explanation:
      "Apollo 11 landed on the Moon on July 20, 1969 — 57 years before 2026. Neil Armstrong's first words were not 'one small step' — he said 'the Eagle has landed' first, then waited six hours before stepping out.",
    source: "https://www.nasa.gov/mission/apollo-11/",
    category: "HISTORY" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-01",
    questionNumber: 154,
    question: "How many people died in the 1918 Spanish Flu pandemic?",
    answer: 50000000,
    unit: "deaths",
    explanation:
      "The 1918 Spanish Flu killed an estimated 50 million people worldwide — more than died in World War I, which had just ended. About one-third of the world's population was infected.",
    source: "https://www.cdc.gov/flu/pandemic-resources/1918-pandemic-h1n1.html",
    category: "HISTORY" as Category,
    difficulty: "medium" as Difficulty,
  },

  // ============================================================
  // WILD CARD (28)
  // ============================================================
  {
    date: "2026-08-02",
    questionNumber: 155,
    question: "How fast can a human sneeze travel, in miles per hour?",
    answer: 100,
    unit: "mph",
    explanation:
      "A sneeze can travel at up to 100 mph and release about 100,000 tiny droplets into the air. That's faster than most highway speed limits — and those droplets can travel up to 27 feet.",
    source: "https://www.lung.org/blog/what-happens-to-your-body-when-you-sneeze",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-03",
    questionNumber: 156,
    question: "How many dimples are on a standard golf ball?",
    answer: 336,
    unit: "dimples",
    explanation:
      "Most standard golf balls have 336 dimples, though the number ranges from 300 to 500 by manufacturer. The dimples reduce aerodynamic drag, helping the ball fly up to 3x farther than a smooth sphere would.",
    source: "https://www.usga.org/content/usga/home-page/rules-hub/rules-modernization/major-changes/equipment-rules.html",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-04",
    questionNumber: 157,
    question: "How many licks does it take to reach the center of a Tootsie Pop?",
    answer: 364,
    unit: "licks",
    explanation:
      "Engineering students at Purdue built a licking machine and found it takes 364 licks on average. Human subjects averaged 252 — but typically bit through the shell before finishing.",
    source: "https://tootsie.com/howmanylick-experiments",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-05",
    questionNumber: 158,
    question: "How many pounds of food does the average American eat per year?",
    answer: 1996,
    unit: "pounds",
    explanation:
      "The average American eats about 1,996 pounds of food per year — nearly a ton. That's approximately 5.5 pounds of food per day, including water content.",
    source: "https://www.ers.usda.gov/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-06",
    questionNumber: 159,
    question: "How many bubbles are in a single glass of champagne?",
    answer: 1000000,
    unit: "bubbles",
    explanation:
      "A single 6-ounce glass of champagne releases about 1 million bubbles. Each bubble starts as a microscopic imperfection in the glass surface. The pressure in a champagne bottle is roughly 3 times that of a car tire.",
    source: "https://www.sciencedirect.com/science/article/pii/S0021979711007643",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-07",
    questionNumber: 160,
    question: "How many pounds does a typical cloud weigh?",
    answer: 1100000,
    unit: "pounds",
    explanation:
      "A typical cumulus cloud weighs about 1.1 million pounds — roughly the weight of 100 elephants. Clouds float because the water droplets are spread out over a huge volume, making their density lower than the surrounding air.",
    source: "https://earthobservatory.nasa.gov/images/47373/how-much-does-a-cloud-weigh",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-08",
    questionNumber: 161,
    question: "How many keys are on a standard piano?",
    answer: 88,
    unit: "keys",
    explanation:
      "A standard piano has 88 keys — 52 white and 36 black. Most modern music uses only the 72 keys in the middle. The extreme high and low keys are rarely played because the notes sound almost inaudible or muddy.",
    source: "https://www.pianoworld.com/fun/88-keys/",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-09",
    questionNumber: 162,
    question: "How many stitches are sewn into a Major League Baseball?",
    answer: 108,
    unit: "stitches",
    explanation:
      "Every official MLB baseball has exactly 108 stitches, made by hand. It takes roughly 15 minutes to sew a baseball. The stitching is what gives pitchers their grip for curveballs, sliders, and fastballs.",
    source: "https://www.mlb.com/news/how-baseballs-are-made",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-10",
    questionNumber: 163,
    question: "How many times per second does a hummingbird flap its wings?",
    answer: 53,
    unit: "times per second",
    explanation:
      "Hummingbirds flap their wings about 53 times per second — creating that characteristic humming sound. Their hearts beat up to 1,260 times per minute during flight. In torpor at night, that drops to just 50 beats per minute.",
    source: "https://www.allaboutbirds.org/news/how-do-hummingbirds-fly/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-11",
    questionNumber: 164,
    question: "How many calories does the average person burn in a day without any exercise?",
    answer: 2000,
    unit: "calories",
    explanation:
      "The average adult burns about 2,000 calories per day just through basic metabolic processes — breathing, circulating blood, maintaining body temperature — even while at rest.",
    source: "https://www.healthline.com/nutrition/how-many-calories-burned-a-day",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-12",
    questionNumber: 165,
    question: "How much does the average American spend on coffee every year, in dollars?",
    answer: 1000,
    unit: "dollars",
    explanation:
      "The average American spends about $1,000 per year on coffee. At $5 per coffee drink, that's about 200 cups per year — roughly 4 per week. Over a 40-year career, that's $40,000 spent on coffee.",
    source: "https://www.statista.com/",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-13",
    questionNumber: 166,
    question: "How many tons does the Statue of Liberty weigh?",
    answer: 225,
    unit: "tons",
    explanation:
      "The Statue of Liberty weighs about 225 tons. The copper skin alone is only about 3/32 of an inch thick — roughly the thickness of two pennies. It turned green through natural oxidation over 20–30 years.",
    source: "https://www.nps.gov/stli/learn/historyculture/statue-statistics.htm",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-14",
    questionNumber: 167,
    question: "How many miles of yarn does it take to knit a typical adult sweater?",
    answer: 2,
    unit: "miles",
    explanation:
      "A standard adult sweater requires about 2 miles (roughly 1,750–2,000 yards) of yarn. A hand-knitter working steadily can knit about 20 stitches per minute — at that rate, a sweater takes 150+ hours of work.",
    source: "https://www.lionbrand.com/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-15",
    questionNumber: 168,
    question: "How many tiny seeds are on the outside of a single strawberry?",
    answer: 200,
    unit: "seeds",
    explanation:
      "A strawberry has about 200 seeds on its surface — making it technically the only fruit that bears its seeds on the outside. Those aren't actually seeds though — botanically, the whole strawberry is a cluster of tiny fruits.",
    source: "https://www.britannica.com/plant/strawberry",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-16",
    questionNumber: 169,
    question: "How many miles can a standard wooden pencil draw a line before running out?",
    answer: 35,
    unit: "miles",
    explanation:
      "A standard pencil can draw a line about 35 miles long before it's fully used up. It can also write approximately 45,000 words, or be sharpened about 17 times.",
    source: "https://www.pencils.com/pencil-facts/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-17",
    questionNumber: 170,
    question: "How many times per second does a honeybee flap its wings?",
    answer: 200,
    unit: "times per second",
    explanation:
      "Honeybees flap their wings about 200 times per second — creating their characteristic buzz. That frequency is precisely why the buzz sounds like the note B-flat. The wings beat fast enough to make the bee sound like a tiny musical instrument.",
    source: "https://www.scientificamerican.com/article/how-do-bees-fly/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-18",
    questionNumber: 171,
    question: "How many gallons of water does it take to produce just one pound of beef?",
    answer: 1800,
    unit: "gallons",
    explanation:
      "Producing one pound of beef requires about 1,800 gallons of water when you account for the water used to grow feed crops, provide drinking water, and process the meat. A single hamburger patty uses roughly 660 gallons.",
    source: "https://www.waterfootprint.org/",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-19",
    questionNumber: 172,
    question: "How many times can you fold a standard piece of paper in half?",
    answer: 7,
    unit: "times",
    explanation:
      "You can fold a standard piece of paper in half a maximum of about 7 times before it becomes too thick and stiff to fold. After 7 folds, it's 128 layers thick. Mathematically, 42 folds would reach the Moon.",
    source: "https://www.sciencealert.com/",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-20",
    questionNumber: 173,
    question: "How many calories are in a standard McDonald's Big Mac?",
    answer: 550,
    unit: "calories",
    explanation:
      "A Big Mac contains 550 calories. McDonald's sells roughly 900 million Big Macs per year in the US alone. The Big Mac Index — comparing Big Mac prices worldwide — is used by economists to measure purchasing power parity.",
    source: "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-21",
    questionNumber: 174,
    question: "How many keys are on a standard full-size computer keyboard?",
    answer: 104,
    unit: "keys",
    explanation:
      "A standard full-size desktop keyboard has 104 keys on a Windows layout (105 for international versions). Laptop keyboards typically have 78–85 keys. The average typist uses only about 50 of them regularly.",
    source: "https://www.mechanical-keyboard.org/switch-types/",
    category: "WILD_CARD" as Category,
    difficulty: "easy" as Difficulty,
  },
  {
    date: "2026-08-22",
    questionNumber: 175,
    question: "How many miles of wire are contained in the cables of the Brooklyn Bridge?",
    answer: 14000,
    unit: "miles",
    explanation:
      "The Brooklyn Bridge's four main cables contain nearly 14,000 miles of steel wire. When it opened in 1883, it was the longest suspension bridge in the world. The chief engineer's wife, Emily Roebling, was the first person to cross it.",
    source: "https://www.nycgovparks.org/parks/brooklyn-bridge-park/history",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-23",
    questionNumber: 176,
    question: "How many nails are used to build the average single-family house?",
    answer: 30000,
    unit: "nails",
    explanation:
      "Building an average single-family home requires roughly 30,000 nails of various sizes. If you laid them end to end, they'd stretch about a third of a mile.",
    source: "https://www.thisoldhouse.com/",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-24",
    questionNumber: 177,
    question: "How many miles of road exist in the United States?",
    answer: 4000000,
    unit: "miles",
    explanation:
      "The US has roughly 4 million miles of roads — the second-largest road network in the world after India. If you drove every road without stopping, at 60 mph it would take about 7.6 years.",
    source: "https://www.fhwa.dot.gov/policyinformation/statistics/2021/hm10.cfm",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-25",
    questionNumber: 178,
    question: "How many gallons of water flow over Niagara Falls every second?",
    answer: 750000,
    unit: "gallons",
    explanation:
      "About 750,000 gallons of water cascade over Niagara Falls every second. Despite this, about half the river's flow is diverted upstream for hydroelectric power generation — particularly at night and in off-season months.",
    source: "https://www.niagarafallstourism.com/niagara-falls/fast-facts/",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-26",
    questionNumber: 179,
    question: "What is the speed of the fastest tennis serve ever recorded, in miles per hour?",
    answer: 163,
    unit: "mph",
    explanation:
      "The fastest tennis serve on record is 163.4 mph, hit by Sam Groth of Australia in 2012. A serve that fast takes about 0.4 seconds to reach the other side of the court — leaving the returner almost no reaction time.",
    source: "https://www.tennishead.net/service-speed-the-fascinating-science-behind-tennis-serves/",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-27",
    questionNumber: 180,
    question: "How many pounds of trash does the average American produce every day?",
    answer: 4.9,
    unit: "pounds",
    explanation:
      "The average American generates about 4.9 pounds of trash per day — among the highest rates in the world. That's nearly 1,800 pounds of garbage per person per year, totaling about 300 million tons nationwide annually.",
    source: "https://www.epa.gov/facts-and-figures-about-materials-waste-and-recycling",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
  {
    date: "2026-08-28",
    questionNumber: 181,
    question: "How many gallons of blood are in a blue whale's body?",
    answer: 220,
    unit: "gallons",
    explanation:
      "A blue whale — the largest animal on Earth — has about 220 gallons of blood in its body. Its heart is the size of a small car and beats just 4–8 times per minute, which can be heard from 2 miles away.",
    source: "https://ocean.si.edu/ocean-life/marine-mammals/blue-whale",
    category: "WILD_CARD" as Category,
    difficulty: "hard" as Difficulty,
  },
  {
    date: "2026-08-29",
    questionNumber: 182,
    question: "How many times bigger is a blue whale than the average adult human, by weight?",
    answer: 2500,
    unit: "times heavier",
    explanation:
      "A blue whale weighs about 200 tons — roughly 2,500 times more than an average 160-pound adult. Its tongue alone weighs as much as an elephant, and a human could fit inside its major arteries.",
    source: "https://ocean.si.edu/ocean-life/marine-mammals/blue-whale",
    category: "WILD_CARD" as Category,
    difficulty: "medium" as Difficulty,
  },
];

export function getTodayQuestion(dateOverride?: string): Question {
  const today = dateOverride || new Date().toISOString().split("T")[0];

  let question = QUESTIONS.find((q) => q.date === today);

  if (!question) {
    const dayOfYear = Math.floor(
      (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) /
        86400000
    );
    question = QUESTIONS[dayOfYear % QUESTIONS.length];
  }

  return { _id: question.date, ...question };
}
